// Code generated by "stringer -type=UniformType gl/types.go"; DO NOT EDIT

package shader

import "fmt"

const _UniformType_name = "TypeInvalidfloatintvec2vec3"

var _UniformType_index = [...]uint8{0, 11, 16, 19, 23, 27}

func (i UniformType) String() string {
	if i >= UniformType(len(_UniformType_index)-1) {
		return fmt.Sprintf("UniformType(%d)", i)
	}
	return _UniformType_name[_UniformType_index[i]:_UniformType_index[i+1]]
}
