// Code generated by "stringer -type=UniformType gl/types.go"; DO NOT EDIT

package gl

import "fmt"

const _UniformType_name = "TypeInvalidTypeFloatTypeIntTypeVec2TypeVec3"

var _UniformType_index = [...]uint8{0, 11, 20, 27, 35, 43}

func (i UniformType) String() string {
	if i >= UniformType(len(_UniformType_index)-1) {
		return fmt.Sprintf("UniformType(%d)", i)
	}
	return _UniformType_name[_UniformType_index[i]:_UniformType_index[i+1]]
}
